# Generated by Django 2.2.4 on 2019-09-02 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190902_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
